### ISSUE TITLE
setting: FE와의 통신 세팅

### ISSUE THREAD

**Issue by Kyeong6** [jnu-sf-engineering/backend-fastapi#12]
## ✏️ Description

- FE와의 통신 세팅을 위한 Docker hub에 이미지 업로드
## 🎟️ Tickets

- [x] FastAPI Dockerfile 작성
- [x] docker-compose-dev.yaml 파일에 FastAPI Dockerfile 반영
- [x] FE 로컬에 Docker hub pull 진행
