### ISSUE TITLE
setting: 개발 환경 세팅

### ISSUE THREAD

**Issue by Kyeong6** [jnu-sf-engineering/backend-fastapi#2]
## ✏️ Description

개발 환경 세팅 진행

## 🎟️ Tickets

- [x] docker-compose를 이용한 MySQL 서버 실행
- [x] MySQL 서버 실행 후 자동 테이블 생성 SQL문 반영 및 테스트
- [x] MySQL 서버 연결 스크립트 작성 후 테스트
- [x] FastAPI 서버 실행 테스트
